# for local templating use helm template . -f values-local.yaml --name-template hubs-keptn --output-dir ../../temp

global:
# use custom image/version e.g. for local testing
  keptn:
    repository: "test/it/like-a-dude"          # keptn registry/image name
    appVersion: xx.xx.xx                       # keptn version/tag

# only change if version at ./charts/control-plane/values.yaml --> apiGatewayNginx.repository/tag is not satisfying
#  apiGatewayNginx:
#    repository: this.is.a.test                 # nginx registry/image name
#    tag: 100.0.0                               # ngnix version/tag